### ISSUE TITLE
初始化yapi报错

### ISSUE THREAD

**Issue by fuwj1994** [Ryan-Miao/docker-yapi#16]
16:32:02 /usr/local/docker-yapi # docker-compose up
WARNING: Found orphan containers (docker-yapi_mongo_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating docker-yapi_yapi_1 ... done
Attaching to docker-yapi_yapi_1
yapi_1  | internal/modules/cjs/loader.js:818
yapi_1  |   throw err;
yapi_1  |   ^
yapi_1  | 
yapi_1  | Error: Cannot find module '/my-yapi/vendors/server/app.js'
yapi_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
yapi_1  |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
yapi_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
yapi_1  |     at internal/main/run_main_module.js:17:47 {
yapi_1  |   code: 'MODULE_NOT_FOUND',
yapi_1  |   requireStack: []
yapi_1  | }
docker-yapi_yapi_1 exited with code 1

**Comment by UpDownXH** [comment]
same issue

**Comment by easy-go-iot** [comment]
第一次启动，要修改配置文件的
![image](https://user-images.githubusercontent.com/117637106/204080313-e664c9a7-b488-491d-a315-4a95d80ca646.png)

**Comment by palp1tate** [comment]
> 第一次启动，要修改配置文件的 ![image](https://user-images.githubusercontent.com/117637106/204080313-e664c9a7-b488-491d-a315-4a95d80ca646.png)

good job!

**Comment by wentao0405** [comment]
> 第一次启动，要修改配置文件的 ![image](https://user-images.githubusercontent.com/117637106/204080313-e664c9a7-b488-491d-a315-4a95d80ca646.png)

爱了
