### ISSUE TITLE
taobao 镜像是过期了吗，无法安装，如何修改

### ISSUE THREAD

**Issue by BaiNan-Y** [Ryan-Miao/docker-yapi#18]
当前安装版本： 1.12.0
连接数据库成功!
开始下载平台文件压缩包...
http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.12.0.tgz
部署文件完成，正在安装依赖库...
npm ERR! code CERT_HAS_EXPIRED npm ERR!
errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npm.taobao.org/ajv failed, reason: certificate has expired
npm
ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2024-03-05T18_22_18_520Z-debug.log
依赖库安装完成，正在初始化数据库mongodb...
> yapi-vendor@1.12.0 install-server /my-yapi/vendors > node server/install.js
Error: internal/modules/cjs/loader.js:818 throw err; ^ Error: Cannot find module 'fs-extra' Require stack: - /my-yapi/vendors/server/install.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.<anonymous> (/my-yapi/vendors/server/install.js:1:12) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) { code: 'MODULE_NOT_FOUND', requireStack: [ '/my-yapi/vendors/server/install.js' ] }

**Comment by Koweiyi** [comment]
同样问题，请问下解决了吗

**Comment by BaiNan-Y** [comment]
未解决，有说是 mongodb 问题的，有说是taobao镜像过期的，使用原生 yapi 搭建好了之后后续还是要有一系列的问题，放弃了

**Comment by cncqw** [comment]
看到一堆npm错误就头疼，这种国产都不成熟的产品不用也罢

**Comment by Kevin-Hunter-K** [comment]
2024年5月12日 遇到了相同的问题

**Comment by Kevin-Hunter-K** [comment]
> 2024年5月12日 遇到了相同的问题

换了好几个版本，都是用的淘宝镜像，都报同样的错，应该是镜像证书过期了
用另外一个docker compose的YApi的开源库部署成功了，也很简单：[yapi](https://github.com/jinfeijie/yapi)
顺利部署

**Comment by xiaoqiang1994** [comment]
1. 进入进入yapi 容器（<yapi-CONTAINER-ID> 替换成你自己的yapi容器id）
`docker exec -it <yapi-CONTAINER-ID> sh `
2. 执行npm忽略证书设置
`npm config set strict-ssl false`
4. 页面开始部署，等待部署完成，进入下一步yaml文件替换启动命令。

**Comment by sparklyi** [comment]
> 1. 进入进入yapi 容器（ 替换成你自己的yapi容器id）
>    `docker exec -it <yapi-CONTAINER-ID> sh `
> 2. 执行npm忽略证书设置
>    `npm config set strict-ssl false`
> 3. 页面开始部署，等待部署完成，进入下一步yaml文件替换启动命令。

成功解决，感谢佬
